PLC_Management/Models/ResultModel/Result.cs
namespace PLC_Management.Models.ResultModel
{
    public class Result
    {
        public int ID { get; set; }
        public string? Parameter_Name { get; set; }
        public string? Parameter_ID { get; set; }
        public string? Parameter_Unit { get; set; }
        public double Value { get; set; }
        public bool Status { get; set; }
        public string? Datetime { get; set; }

        public Result(int iD, string? parameter_Name, string? parameter_ID, string? parameter_Unit, double value, bool status, string? datetime)
        {
            ID = iD;
            Parameter_Name = parameter_Name;
            Parameter_ID = parameter_ID;
            Parameter_Unit = parameter_Unit;
            Value = value;
            Status = status;
            Datetime = datetime;
        }

        public Result(string? parameter_Name, string? parameter_ID, string? parameter_Unit, double value, bool status)
        {
            Parameter_Name = parameter_Name;
            Parameter_ID = parameter_ID;
            Parameter_Unit = parameter_Unit;
            Value = value;
            Status = status;
        }

        public Result()
        {
        }
    }

}

PLC_Management/Controllers/ResultController.cs
using Microsoft.AspNetCore.Mvc;
using PLC_Management.Models.ResultModel;

namespace PLC_Management.Controllers
{
    public class ResultController : Controller
    {
        public IActionResult Index([FromQuery(Name = "tungay")] string tungay, [FromQuery(Name = "toingay")] string toingay, [FromQuery(Name = "page")] int? page, [FromQuery(Name = "pH")] string pH,
            [FromQuery(Name = "Temp")] string Temp, [FromQuery(Name = "TSS")] string TSS, [FromQuery(Name = "COD")] string COD, [FromQuery(Name = "NH4")] string NH4, [FromQuery(Name = "numberResult")] int numberResult)
        {

            if (numberResult>0)
            {
                Common.NUMBER_ELM_ON_PAGE = numberResult;
                if (numberResult > 5000)
                {
                    Common.NUMBER_ELM_ON_PAGE = 5000;
                }
            }

            ResultBusiness resultBusiness = new ResultBusiness();
            List<Result> results = new List<Result>();


            var today = DateTime.Now;
            if (page == null || page == 0)
            {
                page = 1;
            }
            if (tungay == null && toingay == null)
            {
                ViewBag.host = $"result?page=";
                tungay = today.AddDays(-365).ToString("yyyy-MM-dd");
                toingay = today.AddDays(1).ToString("yyyy-MM-dd");
                int sumResult = ResultBusiness.CountResult();

                int countPage = (sumResult / Common.NUMBER_ELM_ON_PAGE);
                if (sumResult % Common.NUMBER_ELM_ON_PAGE != 0)
                {
                    countPage = countPage + 1;
                }
                ViewBag.countPage = countPage;
                try
                {
                    results = resultBusiness.GetAllResults(page);
                }
                catch
                {
                    //Lỗi
                }
                ViewBag.listResults = results;

            }
            else if (tungay != null && toingay != null && (pH == null && Temp == null && TSS == null && COD == null && NH4 == null))
            {

                ViewBag.host = $"result?tungay={tungay}&toingay={toingay}&page=";
                DateTime dateTime1 = Convert.ToDateTime(tungay);
                DateTime dateTime2 = Convert.ToDateTime(toingay).AddDays(1);
                string strDatime1 = dateTime1.Year + "-" + dateTime1.Month + "-" + dateTime1.Day;
                string strDatime2 = dateTime2.Year + "-" + dateTime2.Month + "-" + dateTime2.Day;

                int sumResult = ResultBusiness.CountResultByDay(strDatime1, strDatime2);
                int countPage = (sumResult / Common.NUMBER_ELM_ON_PAGE);
                if (sumResult % Common.NUMBER_ELM_ON_PAGE != 0)
                {
                    countPage = countPage + 1;
                }
                ViewBag.countPage = countPage;

                try
                {
                    results = resultBusiness.GetResultByDay(strDatime1, strDatime2, page);
                }
                catch
                {
                    //Lỗi
                }
                ViewBag.listResults = results;



            }
            else
            {
                string idpH = "pH";
                string idTemp = "Temp";
                string idTSS = "TSS";
                string idCOD = "COD";
                string idNH4 = "NH4";

                idpH = pH != null ? "pH" : "null";
                idTemp = Temp != null ? "Temp" : "null";
                idTSS = TSS != null ? "TSS" : "null";
                idCOD = COD != null ? "COD" : "null";
                idNH4 = NH4 != null ? "NH4" : "null";

                DateTime dateTime1 = Convert.ToDateTime(tungay);
                DateTime dateTime2 = Convert.ToDateTime(toingay).AddDays(1);
                string strDatime1 = dateTime1.Year + "-" + dateTime1.Month + "-" + dateTime1.Day;
                string strDatime2 = dateTime2.Year + "-" + dateTime2.Month + "-" + dateTime2.Day;
                int sumResult = ResultBusiness.CountResultByParameterAndDay(strDatime1, strDatime2, idpH, idTemp, idTSS, idCOD,idNH4);
                int countPage = (sumResult / Common.NUMBER_ELM_ON_PAGE);
                if (sumResult % Common.NUMBER_ELM_ON_PAGE != 0)
                {
                    countPage = countPage + 1;
                }
                ViewBag.countPage = countPage;

                string? hostpH = "";
                string? hostTemp = "";
                string? hostTSS = "";
                string? hostCOD = "";
                string? hostNH4 = "";
                if (pH != null)
                {
                    hostpH = "pH=on&";
                }
                if (Temp != null)
                {
                    hostTemp = "Temp=on&";
                }
                if (TSS != null)
                {
                    hostTSS = "TSS=on&";
                }
                if (COD != null)
                {
                    hostCOD = "COD=on&";
                }
                if(NH4 != null)
                {
                    hostNH4 = "NH4=on&";
                }
                ViewBag.host = $"result?{hostpH}{hostTemp}{hostTSS}{hostCOD}{hostNH4}tungay={tungay}&toingay={toingay}&page=";


                try
                {
                    results = resultBusiness.GetResultByDayAndParameter(strDatime1, strDatime2, idpH,idTemp,idTSS,idCOD,idNH4, page);
                }
                catch
                {
                    //Lỗi
                }
                ViewBag.listResults = results;

            }

            ViewBag.checkpH = pH != null ? "checked" : null;
            ViewBag.checkTemp = Temp != null ? "checked" : null;
            ViewBag.checkTSS = TSS != null ? "checked" : null;
            ViewBag.checkCOD = COD != null ? "checked" : null;
            ViewBag.checkNH4 = NH4 != null ? "checked" : null;


            if (pH == null && Temp == null && TSS == null && COD == null && NH4 == null)
            {
                ViewBag.checkpH = "checked";
                ViewBag.checkTemp = "checked";
                ViewBag.checkTSS = "checked";
                ViewBag.checkCOD = "checked";
                ViewBag.checkNH4 = "checked";
            }
            ViewBag.tungay = tungay;
            ViewBag.toingay = toingay;
            ViewBag.pageCurrent = page;
            ViewBag.NUMBER_ELM_ON_PAGE = Common.NUMBER_ELM_ON_PAGE;

            return View();
        }


        [HttpPost]
        public IActionResult DeleteResult([FromBody] DeleteResultModel deleteResult)
        {
            try
            {
                ResultBusiness.DeleteResultByIDAndParameter(deleteResult.start_id, deleteResult.end_id, deleteResult.pH, deleteResult.Temp, deleteResult.TSS, deleteResult.COD, deleteResult.NH4);

            }
            catch
            {
                //loi xoa
            }
            return Json( new { deleteResult.start_id, deleteResult.end_id, deleteResult.pH, deleteResult.Temp, deleteResult.TSS, deleteResult.COD, deleteResult.NH4 });
        }

        [HttpPost]
        public IActionResult DeleteAllResults()
        {

            try
            {
                ResultBusiness.DeleteAllResults();
                return RedirectToAction("Index");
            }
            catch
            {
                return NotFound();
            }

        }
    }

}

PLC_Management/Views/Result/Index.cshtml
@using PLC_Management.Models.ResultModel
@inject IHttpContextAccessor HttpContextAccessor

@{
    Layout = "_Layout";
}

<link rel="stylesheet" href="~/css/Record.css" />

<div class="row">
    <div class="col-12" style="margin-top:25px;">
        <h1 style="text-align: center;">
            Kết Quả Thu Thập
        </h1>
    </div>

    <div class="col-12" style="margin-top:10px; margin-bottom:10px;">
        <div class="col-12" style="margin-bottom:15px;">
            <select>
                <option value="find_by_day">Lọc theo ngày</option>
            </select>
        </div>

        <form class="search col-12" method="get">
            <div style="margin-bottom:15px;">
                <input id="pH" name="pH" @ViewBag.checkpH type="checkbox" />
                <label style="font-size:18px;font-weight:600;" for="pH">pH</label>
                <input id="Temp" name="Temp" @ViewBag.checkTemp type="checkbox" />
                <label style="font-size:18px;font-weight:600;" for="Temp">Temp</label>
                <input id="TSS" name="TSS" @ViewBag.checkTSS type="checkbox" />
                <label style="font-size:18px;font-weight:600;" for="TSS">TSS</label>
                <input id="COD" name="COD" @ViewBag.checkCOD type="checkbox" />
                <label style="font-size:18px;font-weight:600;" for="COD">COD</label>
                <input id="NH4" name="NH4" @ViewBag.checkNH4 type="checkbox" />
                <label style="font-size:18px;font-weight:600;" for="NH4">NH4</label>
            </div>

            <div class="box_loc">
                <span class="span_locngay">
                    <label style="font-weight:500;" for="tungay">Từ ngày: </label>
                    <input id="tungay" name="tungay" value=@ViewBag.tungay type="date" style="margin-right:40px;" />
                </span>

                <span class="span_locngay">
                    <label style="font-weight:500;" for="toingay">Tới ngày:</label>
                    <input id="toingay" value=@ViewBag.toingay name="toingay" type="date" style="margin-right:40px;" />
                </span>


                <button type="submit" style="padding-left:25px; padding-right:25px;" class="btn-primary btn btn_locngay span_locngay">Lọc</button>
            </div>
        </form>

        @if (@HttpContextAccessor.HttpContext.Session.GetInt32(Common.SESSION_ISADMIN) == 1)
        {
            <div class="col-12" style="display:flex; justify-content:end;">
                <button id="btn_xoa_ban_ghi" type="button" class="btn btn-danger">
                    Xóa bản ghi trang hiện tại
                </button>
            </div>
            <form id="xoa_tat_ca" method="post" asp-controller="Result" asp-action="DeleteAllResults" class="col-12" style="display:flex; justify-content:end; margin-top:10px;">
                <button id="btn_xoa_tat_ca" name="btn_xoa_tat_ca" type="submit" class="btn btn-danger">
                    Xóa tất cả
                </button>
            </form>
        }




        <div class="col-12" style="display:flex; justify-content:space-between; margin-top:25px;">
            <form method="get">
                <input id="numberResult" placeholder="@ViewBag.NUMBER_ELM_ON_PAGE bản ghi" style="text-align:center;width:137px; font-size:14px; height:36px;" name="numberResult" type="number" />
                <button type="submit" class="btn-primary btn">Thay đổi</button>
            </form>
            <div>
                <button class="btn-warning btn" id="btn-print" style="margin-right:10px;">In báo cáo</button>
                <button class="btn-primary btn" id="btn-export">Xuất file excel</button>
            </div>
        </div>

    </div>

    <div class="col-12">
        <div id="print_data">
            <!--Table-->
            <table class="table table-bordered" style="width:100%; text-align:center;" id="table">

                <!--Table head-->
                <thead>
                    <tr>
                        <th>No.</th>
                        <th>Parameter Name</th>
                        <th>ID</th>
                        <th>Unit</th>
                        <th>Date Time</th>
                        <th>Value</th>
                    </tr>
                </thead>
                <!--Table head-->
                <!--Table body-->



                <tbody>
                    @{
                        int i = 0;
                    }
                    @foreach (Result result in ViewBag.listResults)
                    {
                        DateTime dateTime = Convert.ToDateTime(result.Datetime);
                        String s = dateTime.ToString("dd/MM/yyyy HH:mm:ss");
                        int j = i + 1;
                        if (i % 2 == 0)
                        {
                            <tr class="table-success ID_Result" data-id-result="@result.ID">
                                <th scope="row">@j</th>
                                <td>@result.Parameter_Name</td>
                                <td class="Parameter_ID">@result.Parameter_ID</td>
                                <td>@result.Parameter_Unit</td>
                                <td>@s</td>
                                <td>@result.Value</td>
                            </tr>
                        }
                        else
                        {
                            <tr class="ID_Result" data-id-result="@result.ID">
                                <th scope="row">@j</th>
                                <td>@result.Parameter_Name</td>
                                <td class="Parameter_ID">@result.Parameter_ID</td>
                                <td>@result.Parameter_Unit</td>
                                <td>@s</td>
                                <td>@result.Value</td>
                            </tr>
                        }
                        i++;
                    }

                </tbody>
                <!--Table body-->





            </table>
        </div>
        <!--Table-->
        <div class="col-12" style="display: flex; justify-content:space-between; margin-top:15px;margin-bottom:25px;">
            <div>
                <div>
                    <nav aria-label="...">
                        <ul class="pagination">
                            @{
                                int page1 = ViewBag.pageCurrent - 2;
                                int page2 = ViewBag.pageCurrent - 1;
                                int page3 = ViewBag.pageCurrent;
                                int page4 = ViewBag.pageCurrent + 1;
                                int page5 = ViewBag.pageCurrent + 2;


                                string link1 = @ViewBag.host + page1;
                                string link2 = @ViewBag.host + page2;
                                string link3 = @ViewBag.host + page3;
                                string link4 = @ViewBag.host + page4;
                                string link5 = @ViewBag.host + page5;

                                string link_count_page = @ViewBag.host + @ViewBag.countPage;
                            }
                            @if ((@page3 - 2) > 0)
                            {
                                <li class="page-item"><a class="page-link" href="./@link1">@page1</a></li>
                            }
                            @if ((@page3 - 1) > 0)
                            {
                                <li class="page-item"><a class="page-link" href="./@link2">@page2</a></li>
                            }

                            <li class="page-item active"><a class="page-link" href="./@link3">@page3</a></li>

                            @if (@page3 < @ViewBag.countPage)
                            {
                                <li class="page-item"><a class="page-link" href="./@link4">@page4</a></li>
                            }

                            @if ((@page3 + 1) < @ViewBag.countPage)
                            {
                                <li class="page-item"><a class="page-link" href="./@link5">@page5</a></li>
                            }
                            @if ((@page3 + 2) < @ViewBag.countPage)
                            {
                                <li style="width:28px; display: flex; justify-content:center; font-size:19px; height:100%; margin-top:9px; color:#0d6efd ">. . .</li>
                                <li class="page-item"><a class="page-link" href="./@link_count_page">@ViewBag.countPage (hết)</a></li>
                            }

                        </ul>
                    </nav>
                </div>




            </div>

            <div style="height:35px;">
                <input data-go-page="@ViewBag.countPage" style="width:100px; height:100%; text-align:center" placeholder="Trang số ..." type="number" id="input_go_page" />
                <button data-go-page="@ViewBag.host" class="btn-primary btn" style="height:calc(100%+5px);" id="btn_go_page" type="button">Đi tới trang</button>
            </div>

        </div>
    </div>

</div>






<script src="./js/table2excel.js"></script>
<script>
    const table2excel = new Table2Excel();
    document.querySelector("#btn-export").addEventListener("click", () => {
        table2excel.export(document.querySelector("#table"));
    })
</script>
<script src="~/js/PrintResult.js"></script>
<script src="~/js/Pagination.js"></script>
<script src="~/js/DeleteResult.js"></script>